### ISSUE TITLE
Enabling corfu-doc-mode in init.el errors when running emacs as daemon

### ISSUE THREAD

**Issue by accelbread** [galeo/corfu-doc#17]
After updating the package today, the `(corfu-doc-mode)` line in my init.el works when emacs is started normally, but errors when emacs is started as a daemon. This is likely because when running as daemon, no frame is available while running init.el.

The exact error I get is as follows:
```
Warning (initialization): An error occurred while loading ‘/home/archit/.config/emacs/init.el’:

error: Corfu-doc requires child frames to display documentation
```
Emacs continues after the error but does not load the rest of init.el and shows the above error in the messages buffer.

I am using emacs 29 on Linux.

**Comment by galeo** [comment]
Please run emacs in GUI mode. You may want to have a look at the **corfu-doc-terminal** package.

**Comment by galeo** [comment]
Please have a try with the latest code and see if this issue has been resolved. Thanks.

**Comment by gwbrck** [comment]
How do I set corfu-doc up, when using emacs as server? I am using GUI mode almost exclusively, but when I am starting the daemon and corfu-doc is initialised (display-graphic-p) is nil.

**Comment by galeo** [comment]
corfu and corfu-doc both require child frames to display the popup. Thus make sure run emacs in GUI mode. You can simply set them up with the code below.

```elisp
(add-hook 'corfu-mode-hook #'corfu-doc-mode)
(when (display-graphic-p)
  (global-corfu-mode))
``` 

They will be turned off in TUI mode.

**Comment by gwbrck** [comment]
@galeo thanks for the suggestion! 
Sadly, this doesn't work with emacs deamon. This is because (at least that's my understanding) at the moment when emacs as daemon loads the init file, emacs is running neither as TUI nor as GUI. So (display-graphic-p) equals to nil. When a GUI-frame is created and (display-graphics-p) equals to t the init.el file had been run already. I tried something with after-make-frame-functions and this works. But somehow this doesn't work for the initial frame. 

I mean, it perfectly works for me with just enabling (global-corfu-mode) in the init-file. Without checking for (display-graphics-p). But then I got these Warnings about Corfu-Doc requires child frames. But other than that, Corfu doc works as expected... 

I don't know if using the after-make-frame-functions hook is the right approach for starting up global-corfu-mode and respectively corfu-docs. What do you think? Is there a proper way of using corfu-mode with corfu-doc with emacs server?

**Comment by gwbrck** [comment]
this works: 

```elisp
  (defun safe-global-corfu-mode ()
    (when (display-graphic-p)
      (global-corfu-mode)))
  (if (daemonp)
      (add-hook 'server-after-make-frame-hook #'safe-global-corfu-mode)
    (safe-global-corfu-mode))
```
idk if there is an easier or better way...

**Comment by galeo** [comment]
Hi @gwbrck I delete the code that displays the warning when child frame is not supported. Please try the latest code in main branch.  Thanks.

**Comment by gwbrck** [comment]
Thank you!
