### ISSUE TITLE
Please provide clearer information on migration in README

### ISSUE THREAD

**Issue by ksqsf** [galeo/corfu-doc#25]
> Important: this package has been merged into Corfu as one of its [extensions](https://github.com/minad/corfu#extensions). And this repository is deprecated now.

"one of its extensions" is unnecessarily vague. Please at least say which extension.

**Comment by galeo** [comment]
Currently It's [corfu-popupinfo](https://github.com/minad/corfu/blob/main/extensions/corfu-popupinfo.el). 

> ;; NOTE: This extension has been added recently to Corfu. It is still
> ;; experimental. The extension may get renamed and the public interface
> ;; may change any time.

I didn't give a specific name because of the caveat above. I see this warning was just removed, but not sure if it will change in the future. Therefore, the current statement I think is reasonable.
